### ISSUE TITLE
OpenSSL-related compile error

### ISSUE THREAD

**Issue by ajmazurie** [pegasus-isi/homebrew-tools#1]
Hi guys,
I was pleasantly surprised to discover that I could install Pegasus and HTCondor with my favorite package manager, Homebrew. However I go the following error message when installing the former:

```
Last 15 lines from /Users/ajmazurie/Library/Logs/Homebrew/pegasus/01.ant:
     [exec] 
     [exec] In file included from OpenSSL/crypto/crypto.c:16:
     [exec] In file included from OpenSSL/crypto/crypto.h:30:
     [exec] OpenSSL/crypto/x509.h:17:10: fatal error: 'openssl/ssl.h' file not found
     [exec] #include <openssl/ssl.h>
     [exec]          ^
     [exec] 1 error generated.
     [exec] error: command 'clang' failed with exit status 1
     [exec] make: *** [/private/tmp/pegasus20160415-73028-1xl8h8o/pegasus-source-4.6.0/lib/pegasus/externals/python/OpenSSL] Error 1
     [exec] make: *** Waiting for unfinished jobs....
```

For information, I have the `openssl` package installed. However Homebrew warns of the following:

```
Apple has deprecated use of OpenSSL in favor of its own TLS and crypto libraries

Generally there are no consequences of this for you. If you build your
own software and it requires this formula, you'll need to add to your
build variables:

    LDFLAGS:  -L/usr/local/opt/openssl/lib
    CPPFLAGS: -I/usr/local/opt/openssl/include
```

I'm guessing that I should take this into consideration when building Pegasus with Homebrew, but I'm not sure how. Any suggestion?

Best, Aurélien

**Comment by juve** [comment]
Looks like it is trying to install pyOpenSSL, which happens for OSX < El Capitan. What does this give you?

```
$ /usr/bin/sw_vers -productVersion
```

How about this?

```
$ python -c "import OpenSSL"
```

**Comment by ajmazurie** [comment]
I get 10.10.5 for the first command, and an ImportError exception "No module named OpenSSL" for the second.

**Comment by juve** [comment]
@ajmazurie can you try:

```
$ brew update
$ brew install --devel pegasus
```

And see if that solves your issue? It requires --devel because had to make some changes to Pegasus to fix it in addition to the changes to the formula.

**Comment by juve** [comment]
This is the related Pegasus issue: https://jira.pegasus.isi.edu/browse/PM-997

**Comment by ajmazurie** [comment]
This appears to work; I could launch `pegasus-version` and got 4.6.1dev as answer. Let me know if there is another test I can launch.

**Comment by juve** [comment]
Great! The Pegasus 4.6.1 release next week will include this fix. Until then it should be OK to use 4.6.1dev. If you have problems upgrading open another issue or email pegasus-support@isi.edu.
