### ISSUE TITLE
homebrew fails on ant clean dist-common doc-user-guide

### ISSUE THREAD

**Issue by harryhoch** [pegasus-isi/homebrew-tools#10]
hello, folks..

I tried to install via homebrew as documented [on the site](https://pegasus.isi.edu/downloads/), and got this error:

==> Pouring tox--4.4.8.ventura.bottle.tar.gz
🍺  /usr/local/Cellar/tox/4.4.8: 1,202 files, 22MB
==> Installing pegasus-isi/tools/pegasus@5
==> ant clean dist-common doc-user-guide
Last 15 lines from /Users/harry/Library/Logs/Homebrew/pegasus@5/01.ant:
     [exec] docs: install_package> python -I -m pip install --force-reinstall --no-deps /private/tmp/pegasusA5-20230403-23210-97j30x/pegasus-5.0.5/packages/pegasus-python/.tox/.tmp/package/1/pegasus-wms-5.0.5.tar.gz
     [exec] docs: commands_pre[0] /private/tmp/pegasusA5-20230403-23210-97j30x/pegasus-5.0.5/doc/sphinx> sphinx-apidoc --force --implicit-namespaces --output-dir python /private/tmp/pegasusA5-20230403-23210-97j30x/pegasus-5.0.5/packages/pegasus-python/../pegasus-api/src/Pegasus
     [exec] Creating file python/Pegasus.rst.
     [exec] Creating file python/Pegasus.api.rst.
     [exec] Creating file python/modules.rst.
     [exec] docs: commands[0] /private/tmp/pegasusA5-20230403-23210-97j30x/pegasus-5.0.5/doc/sphinx> make html man
     [exec] docs: failed with make is not allowed, use allowlist_externals to allow it
     [exec] .pkg: _exit> python /usr/local/Cellar/tox/4.4.8/libexec/lib/python3.11/site-packages/pyproject_api/_backend.py True setuptools.build_meta
     [exec]   docs: FAIL code 1 (44.51 seconds)
     [exec]   evaluation failed :( (44.63 seconds)

Running OS X Venture 13.1.

**Comment by mayani** [comment]
It seems some code changes will be required to support the latest version of tox.

Can you try adding the `--without-manpages` option?

**Comment by harryhoch** [comment]
thanks. that worked.
