### ISSUE TITLE
Pegasus won't install via homebrew on Mac OS X 10.11.6

### ISSUE THREAD

**Issue by jblowe** [pegasus-isi/homebrew-tools#4]
I'm trying to install Pegasus on my Macbook Pro (Mac OS X 10.11.6 El Capitan).

I am getting an error 'unable to parse pegasus-dax-validator.xml'. 

If I try to install it a second time, I get a different error (see below).

Am I doing something wrong?

I am attaching
[01.ant.txt](https://github.com/pegasus-isi/homebrew-tools/files/1975286/01.ant.txt)
 01.ant, which seems to contain even more errors...

$ brew install pegasus htcondor
Warning: pegasus-isi/tools/htcondor 8.4.4 is already installed and up-to-date
To reinstall 8.4.4, run `brew reinstall htcondor`
==> Installing pegasus from pegasus-isi/tools
==> Downloading https://download.pegasus.isi.edu/pegasus/4.8.2/pegasus-4.8.2.tar.gz
######################################################################## 100.0%
==> ant clean dist-common doc-manpages
Last 15 lines from /Users/jblowe/Library/Logs/Homebrew/pegasus/01.ant:
     [exec]                   ^
     [exec] Entity: line 4: 
     [exec] 	format		() #IMPLIED
     [exec] 	      		 ^
     [exec] unable to parse pegasus-dax-validator.xml
     [exec] make: *** [pegasus-dax-validator.1] Error 6
     [exec] make: *** Waiting for unfinished jobs....
     [exec] Note: Writing pegasus-keg.1
     [exec] Note: Writing pegasus-kickstart.1
     [exec] Note: Writing pegasus-metadata.1

BUILD FAILED
/private/tmp/pegasus-20180504-31438-11w42mq/pegasus-4.8.2/build.xml:211: exec returned: 2

Total time: 2 minutes 34 seconds

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
https://github.com/pegasus-isi/homebrew-tools/issues

$ brew install pegasus
==> Installing pegasus from pegasus-isi/tools
==> Downloading https://download.pegasus.isi.edu/pegasus/4.8.2/pegasus-4.8.2.tar.gz
Already downloaded: /Users/jblowe/Library/Caches/Homebrew/pegasus-4.8.2.tar.gz
==> ant clean dist-common doc-manpages
Last 15 lines from /Users/jblowe/Library/Logs/Homebrew/pegasus/01.ant:
     [exec] Note: Writing pegasus-rc-client.1
     [exec] error : Operation in progress
     [exec] warning: failed to load external entity "http://docbook.sourceforge.net/release/xsl/current/html/chunker.xsl"
     [exec] compilation error: file http://docbook.sourceforge.net/release/xsl/current/html/docbook.xsl line 71 element include
     [exec] xsl:include : unable to load http://docbook.sourceforge.net/release/xsl/current/html/chunker.xsl
     [exec] make: *** [pegasus-kickstart.1] Error 5
     [exec] make: *** Waiting for unfinished jobs....
     [exec] make: *** [pegasus-metadata.1] Error 5
     [exec] Note: Writing pegasus-remove.1
     [exec] Note: Writing pegasus-run.1

BUILD FAILED
/private/tmp/pegasus-20180504-34768-zpr4al/pegasus-4.8.2/build.xml:211: exec returned: 2

Total time: 3 minutes 28 seconds

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
https://github.com/pegasus-isi/homebrew-tools/issues

**Comment by mayani** [comment]
Hi @jblowe 

I was able to install the package without issue.

Logs show following
```
 warning: failed to load external entity "http://docbook.sourceforge.net/release/xsl/current/html/division.xsl"
     [exec] compilation error: file http://docbook.sourceforge.net/release/xsl/current/html/docbook.xsl line 53 element include
     [exec] xsl:include : unable to load http://docbook.sourceforge.net/release/xsl/current/html/division.xsl
     [exec] xsltproc -xinclude docbook-man.xsl pegasus-run.xml
     [exec] Note: Writing pegasus-rc-client.1
     [exec] error : Operation in progress
     [exec] warning: failed to load external entity "http://docbook.sourceforge.net/release/xsl/current/html/chunker.xsl"
     [exec] compilation error: file http://docbook.sourceforge.net/release/xsl/current/html/docbook.xsl line 71 element include
     [exec] xsl:include : unable to load http://docbook.sourceforge.net/release/xsl/current/html/chunker.xsl
     [exec] make: *** [pegasus-kickstart.1] Error 5
```

The documentation generation step needs external resources, which could not be fetched from SourceForge. Different log traces for different runs also indicate issue with the external resource.

I suspect retrying at a later time should fix the issue. If it does not work please re-include the log for it as well, i.e. 01.ant.txt

**Comment by jblowe** [comment]
Ok, I tried again a couple times and it finally worked. (I think I must have some sort of connectivity problem.)

I did, however, get another errors, which _seems_ to be harmless:

Already downloaded: /Users/jblowe/Library/Caches/Homebrew/pegasus-4.8.2.tar.gz
==> ant clean dist-common doc-manpages
Error: Calling <<-EOS.undent is disabled!
Use <<~EOS instead.
/usr/local/Homebrew/Library/Taps/pegasus-isi/homebrew-tools/pegasus.rb:78:in `caveats'
Please report this to the pegasus-isi/tools tap!
Or, even better, submit a PR to fix it!
