### ISSUE TITLE
Issue Installing HTCondor using brew command

### ISSUE THREAD

**Issue by Argindm** [pegasus-isi/homebrew-tools#8]
Hello,
I'm having a problem installing htcondor through brew command. Here's the screenshot of the error I get. 

<img width="691" alt="Screen Shot 2021-03-28 at 2 55 59 PM" src="https://user-images.githubusercontent.com/75541611/112769468-fcfa4c00-8fd5-11eb-9239-12e0b938f152.png">

**Comment by mayani** [comment]
HTCondor released a new stable version 8.8.13, which seems to have fixed the issue. Can you retry installing.
