### ISSUE TITLE
Error installing with Homebrew - docs: commands failed

### ISSUE THREAD

**Issue by hluetck** [pegasus-isi/homebrew-tools#9]
Hello,

I am trying to install Pegasus with Homebrew on macOS 10.15.7. The build fails with the error below. 

Thanks for any hints!

==> Installing pegasus-isi/tools/pegasus@5
==> ant clean dist-common doc-user-guide
Last 15 lines from /Users/henry/Library/Logs/Homebrew/pegasus@5/01.ant:
     [exec] dumping object inventory... done
     [exec] build succeeded, 31 warnings.
     [exec]
     [exec] The HTML pages are in _build/html.
     [exec] Documentation build contained warnings, which we do not allow. Summary (more above):
     [exec] checking consistency... /private/tmp/pegasusA5-20210924-24320-1ch6fh0/pegasus-5.0.0/doc/sphinx/python/Pegasus.rst: WARNING: document isn't included in any toctree
     [exec] make: *** [html] Error 1
     [exec] ERROR: InvocationError for command /usr/local/Homebrew/Library/Homebrew/shims/mac/super/make html man (exited with code 2)
     [exec] ___________________________________ summary ____________________________________
     [exec] ERROR:   docs: commands failed

BUILD FAILED
/private/tmp/pegasusA5-20210924-24320-1ch6fh0/pegasus-5.0.0/build.xml:333: exec returned: 1

**Comment by mayani** [comment]
Hi @hluetck, 

Can you try adding the `--without-manpages` option?

**Comment by hluetck** [comment]
Yes, this worked. Thanks for your help!
